### ISSUE TITLE
Create's dough missing recipe

### ISSUE THREAD

**Issue by VML8** [celsiusqc/Create-Dimensions#2]
Both crafting and washing recipes for the dough are missing.
![image](https://user-images.githubusercontent.com/92667459/218336639-e4106c08-7ef7-4d53-b4a6-9d5b84a2a3a6.png)
Washing wheat flour using encased fan makes them disappear.
![Screenshot_20230212_074429](https://user-images.githubusercontent.com/92667459/218337000-6e577b83-6d8a-43ee-a04b-9de6b262d2a1.png)
![Screenshot_20230212_074455](https://user-images.githubusercontent.com/92667459/218337005-64355faf-3103-4dac-8dc8-e28ba254a76a.png)

**Comment by celsiusqc** [comment]
Fixed in upcoming major version
