### ISSUE TITLE
Scoria

### ISSUE THREAD

**Issue by Paledivine** [celsiusqc/Create-Dimensions#4]
Scoria and Soul Stone have overlapping recipes in the furnace.

**Comment by Paledivine** [comment]
Also in Bulk Blasting

**Comment by celsiusqc** [comment]
What do you mean? Please provide screenshots

**Comment by Paledivine** [comment]
![image](https://user-images.githubusercontent.com/125704669/220123548-accf8483-6975-4e34-8233-1002933ea27c.png)
![image](https://user-images.githubusercontent.com/125704669/220123589-aed3f742-120e-487b-ae8f-266b7d22db30.png)

**Comment by celsiusqc** [comment]
I'll fix it in the next major version. Thanks for bringing this to my attention.

**Comment by celsiusqc** [comment]
Fixed in upcoming major version
